// <auto-generated />
using ATM_DEMO_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ATM_DEMO_API.Migrations;

[DbContext(typeof(BankContext))]
[Migration("20230426162739_Init_BankDB")]
partial class Init_BankDB
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "6.0.16")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

        modelBuilder.Entity("ATM_DEMO_API.Models.BankUserInfo", b =>
            {
                b.Property<string>("CardID")
                    .HasColumnType("VARCHAR(19)");

                b.Property<decimal>("Money")
                    .HasColumnType("DECIMAL(12,0)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("NVARCHAR(50)");

                b.HasKey("CardID");

                b.ToTable("BankUserInfo");

                b.HasData(
                    new
                    {
                        CardID = "4122-8934-5678-9010",
                        Money = 10000000m,
                        Name = "Le Thanh"
                    });
            });

        modelBuilder.Entity("ATM_DEMO_API.Models.BankUserLoginInfo", b =>
            {
                b.Property<string>("CardID")
                    .HasColumnType("VARCHAR(19)");

                b.Property<string>("PIN")
                    .IsRequired()
                    .HasColumnType("VARCHAR(6)");

                b.HasKey("CardID");

                b.ToTable("BankUserLoginInfo");

                b.HasData(
                    new
                    {
                        CardID = "4122-8934-5678-9010",
                        PIN = "654321"
                    });
            });

        modelBuilder.Entity("ATM_DEMO_API.Models.BankUserLoginInfo", b =>
            {
                b.HasOne("ATM_DEMO_API.Models.BankUserInfo", "BankUserInfo")
                    .WithOne("BankUserLoginInfo")
                    .HasForeignKey("ATM_DEMO_API.Models.BankUserLoginInfo", "CardID")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("BankUserInfo");
            });

        modelBuilder.Entity("ATM_DEMO_API.Models.BankUserInfo", b =>
            {
                b.Navigation("BankUserLoginInfo");
            });
#pragma warning restore 612, 618
    }
}
